### ISSUE TITLE
 <rejected> Error: Error: Cannot find module '@discordjs/opus

### ISSUE THREAD

**Issue by ZipZash** [LegendNed/Donnie-Thornberry-bot#1]
Bot can join and leave the voice channel, however it doesn't play any audio.
I installed everything, node, npm, and yarn but still doest work
Opus seems to either not being installed or just cannot be found in the code.
in my @discordjs folder there is only collection and form-data folders.
I included the error code that my command prompt gives me for windows.

    at Object.loader [as require] (C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\util\loader.js:12:9)
    at loadOpus (C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\opus\Opus.js:17:17)
    at new OpusStream (C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\opus\Opus.js:46:10)
    at new Encoder (C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\opus\Opus.js:149:5)
    at AudioPlayer.playPCMStream (C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\player\BasePlayer.js:58:34)
    at AudioPlayer.playUnknown (C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\player\BasePlayer.js:53:17)
    at VoiceConnection.play (C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\util\PlayInterface.js:71:28)
    at Client.<anonymous> (C:\Users\adria\Donnie-Thornberry-bot\index.js:31:36)
    at Client.emit (events.js:315:20)
    at VoiceConnection.onSpeaking (C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\VoiceConnection.js:516:21) Promise {
rejected Error: Error: Cannot find module '@discordjs/opus'
  Require stack:
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\util\loader.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\opus\Opus.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\opus\index.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\index.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\player\BasePlayer.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\player\BroadcastAudioPlayer.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\VoiceBroadcast.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\ClientVoiceManager.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\Client.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\index.js
  - C:\Users\adria\Donnie-Thornberry-bot\index.js
  Error: Cannot find module 'node-opus'
  Require stack:
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\util\loader.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\opus\Opus.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\opus\index.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\index.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\player\BasePlayer.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\player\BroadcastAudioPlayer.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\VoiceBroadcast.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\ClientVoiceManager.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\Client.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\index.js
  - C:\Users\adria\Donnie-Thornberry-bot\index.js
  Error: Cannot find module 'opusscript'
  Require stack:
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\util\loader.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\opus\Opus.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\opus\index.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\index.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\player\BasePlayer.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\player\BroadcastAudioPlayer.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\VoiceBroadcast.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\ClientVoiceManager.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\Client.js
  - C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\index.js
  - C:\Users\adria\Donnie-Thornberry-bot\index.js
      at Object.loader [as require] (C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\util\loader.js:12:9)
      at loadOpus (C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\opus\Opus.js:17:17)
      at new OpusStream (C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\opus\Opus.js:46:10)
      at new Encoder (C:\Users\adria\Donnie-Thornberry-bot\node_modules\prism-media\src\opus\Opus.js:149:5)
      at AudioPlayer.playPCMStream (C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\player\BasePlayer.js:58:34)
      at AudioPlayer.playUnknown (C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\player\BasePlayer.js:53:17)
      at VoiceConnection.play (C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\util\PlayInterface.js:71:28)
      at Client.<anonymous> (C:\Users\adria\Donnie-Thornberry-bot\index.js:31:36)
      at Client.emit (events.js:315:20)
      at VoiceConnection.onSpeaking (C:\Users\adria\Donnie-Thornberry-bot\node_modules\discord.js\src\client\voice\VoiceConnection.js:516:21)
}

**Comment by ZipZash** [comment]
After research from others having the same issue. Installing Opus directly seemed to help me solve the issue.
while inside the folder use the command:
$ npm i @discordjs/opus
and restart the bot and it finally worked for me
